# Generated by Django 6.1.1 on 2026-09-30 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField(blank=True, null=True)),
                ('generated_sql', models.TextField(blank=True, null=True)),
                ('executed_sql', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('explained_only', 'Explained Only'), ('generated_only', 'Generated Only')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_manager.databaseconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('tables_used', models.JSONField(default=list)),
                ('sql_operations', models.JSONField(default=list)),
                ('line_by_line', models.JSONField(default=list)),
                ('clause_breakdown', models.JSONField(default=dict)),
                ('technical_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='query_assistant.queryhistory')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.IntegerField(default=100)),
                ('optimization_suggestions', models.JSONField(default=list)),
                ('index_recommendations', models.JSONField(default=list)),
                ('query_complexity', models.CharField(default='Low', max_length=50)),
                ('cost_reduction_tips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimization', to='query_assistant.queryhistory')),
            ],
        ),
    ]
